version: "3"
services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: db_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"
    volumes:
      - ./server/todo-api/postgres-table-init.sql:/docker-entrypoint-initdb.d/postgres-table-init.sql
  api:
    build: ./server/todo-api
    container_name: api_todo_container
    links:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./server/todo-api:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_NAME: todo
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  client:
    stdin_open: true
    build: ./client/todo
    container_name: react-todo-app
    ports:
      - "3001:3000"
